apiVersion: v2
name: openldap-stack-ha
dependencies:
  - name: ltb-passwd
    version: 0.1.x
    condition: ltb-passwd.enabled
  - name: phpldapadmin
    version: 0.1.x
    condition: phpldapadmin.enabled
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: ~2
home: https://www.openldap.org
version: 4.3.3
appVersion: 2.6.9
description: Community developed LDAP software
icon: https://raw.githubusercontent.com/reprostat/helm-openldap/master/logo.png
keywords:
  - ldap
  - openldap
  - iam-stack
  - high availability
sources:
  - https://github.com/reprostat/helm-openldap
maintainers:
  - name: Tibor Auer
    email: tibor.auer@gmail.com
engine: gotpl
