# Default values for openldap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global Docker image parameters
# Please, note that this will override the image parameters, including dependencies, configured to use the global value
# Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  #imagePullSecrets: [""]
  ldapDomain: "dc=example,dc=org"
  # Specifies an existing secret to be used for admin and config user passwords. The expected key are LDAP_ADMIN_PASSWORD and LDAP_CONFIG_ADMIN_PASSWORD.
  # existingSecret: ""
  ## Default Passwords to use, stored as a secret. Not used if existingSecret is set.
  adminPassword: Not@SecurePassw0rd
  replicationPassword: Not@SecurePassw0rd
  ldapPort: 389
  sslLdapPort: 636
  # Allow access to the config database (cn=config) for the admin user. This is required for configuring logging and accesslog.
  allowConfigAccess: false
  # Allow anonymous access to the LDAP server. This may be required for some applications that need to read the LDAP tree without authentication.
  allowAnonymousAccess: true
  # The name of a kubernetes.io/tls type secret to use for TLS
  tlsSecret: "" 

## @section Common parameters

## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

# Existing configmap with custom schema files used to be used in addition to default schemas
# Can't be use with customSchemaFiles
# customSchemaCm: my-custom-schema-cm
#
# Custom openldap schema files used to be used in addition to default schemas
# Note that the supplied files are sorted by name and inserted into 'LDAP_EXTRA_SCHEMAS' env var
# after chart default schemas, allowing you to control the loading sequence.
# customSchemaFiles:
#   custom.ldif: |-
#     # custom schema
#   anothercustom.ldif: |-
#     # another custom schema

## Existing configmap with custom ldif
# Can't be use with customLdifFiles
# Same format as customLdifFiles
# customLdifCm: my-custom-ldif-cm

# Custom openldap configuration files used to override default tree
# The supplied files MUST have the names "root.ldif" and "entries.ldif", otherwise they will be ignored.
# customLdifFiles:
#   root.ldif: |-
#     # Root creation
#     dn: dc=example,dc=org
#     objectClass: dcObject
#     objectClass: organization
#     o: Example, Inc
#   entries.ldif: |-
#     dn: cn=myGroup,dc=example,dc=org
#     cn: myGroup
#     gidnumber: 500
#     objectclass: posixGroup
#     objectclass: top
#
#     dn: cn=Jean Dupond,dc=example,dc=org
#     cn: Jean Dupond
#     gidnumber: 500
#     givenname: Jean
#     homedirectory: /home/users/jdupond
#     objectclass: inetOrgPerson
#     objectclass: posixAccount
#     objectclass: top
#     sn: Dupond
#     uid: jdupond
#     uidnumber: 1000
#     userpassword: {MD5}KOULhzfBhPTq9k7a9XfCGw==

# Custom openldap ACLs
# If not defined, the following default ACLs are applied:
# customAcls: |-
#   dn: olcDatabase={2}mdb,cn=config
#   changetype: modify
#   replace: olcAccess
#   olcAccess: {0}to *
#     by dn.exact=gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth manage
#     by * break
#   olcAccess: {1}to attrs=userPassword,shadowLastChange
#     by self write
#     by dn="{{ include "global.bindDN" . }}" write
#     by anonymous auth by * none
#   olcAccess: {2}to *
#     by dn="{{ include "global.bindDN" . }}" write
#     by self read
#     by * none

passwordPolicy:
  groupSubDN: ou=pwdpolicies
  configPPM: |-
    minQuality 4
    forbiddenChars .$§€£äöüß
    checkRDN 1
    checkAttributes mail
  expiry: 15552000 # ~6 months [seconds]
  warn_before_expiry: 604800 # 1 week [seconds]
  min_length: 12
  max_attempt: 5
  lockout: 300 # [seconds]; 0 = infinite -> password reset required

logging:
  logFile: /var/lib/ldap/slapd.log
  # Accepted log formats: "debug", "syslog-utc" or "syslog-localtime"
  logFormat: debug
  # For valid log levels: see https://openldap.org/doc/admin26/slapdconfig.html#loglevel%20%3Clevel%3E
  logLevel: "config stats"
  logRotate:
    count: 7 # number of rotated log files to keep
    size: 50 # [megabytes]
    hours: 24 # rotate every 24 hours

# Initial and daily backups
backup:
  schedule: ""
  file: ""
  # Daily time in 24-hour "HH:MM" format. If empty, the daily backup is disabled.
  # schedule: "02:00"
  # Location of the backup file. If empty, all backups are disabled.
  # file: /var/lib/ldap/backup.ldif

adminGroupSubDN: cn=global-admins,ou=groups
useRfc2307bisSchema: false
accessLog:
  enabled: false
  dataDir: /var/lib/ldap/accesslog
  # Accepted values are "writes", "reads", "session", "all", or a combination of them separated by spaces.
  operations: writes reads
  purgeSchedule: 1 # scan the accesslog DB every 1 day
  purgeAge: 7 # purge entries older than 7 days

replication:
  writeableReplicaCount: 1 # MUST be at least 1. Multiple writeable replicas implemented using mirror mode.
  readOnlyReplicaCount: 0 # TODO
  # Uses pod anti-affinity to ensure that the pods are scheduled on different nodes. If you want to disable this, set to false.
  multipleNodes: false


image:
  repository: vegardit/openldap
  tag: "2.6.10"
  pullPolicy: Always
  pullSecrets: []

## OPENLDAP  resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## @param resources.limits The resources limits for the OPENLDAP  containers
## @param resources.requests The requested resources for the OPENLDAP  containers
##
resources:
  requests: {}
#  requests:
#    cpu: 200m
#    memory: 128Mi
  limits: {}
#  limits:
#    cpu: 300m
#    memory: 256Mi

## Persist data to a persistent volume
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "standard-singlewriter"
  # existingClaims:
  #  config: openldap-config
  #  data: openldap-data
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  storageClass: ""

## @param extraEnvVars Array with extra environment variables to add to OPENLDAP  nodes
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []
## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars for OPENLDAP  nodes
##
extraEnvVarsCM:
## @param extraEnvVarsSecret Name of existing Secret containing extra env vars for OPENLDAP  nodes
##
extraEnvVarsSecret:
## @param extraVolumes Optionally specify extra list of additional volumes for the OPENLDAP  pod(s)
##
extraVolumes: []
## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for the OPENLDAP  container(s)
##
extraVolumeMounts: []
## @param sidecars Add additional sidecar containers to the OPENLDAP  pod(s)
## e.g:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: {}
## @param initContainers Add additional init containers to the OPENLDAP  pod(s)
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
## e.g:
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ['sh', '-c', 'echo "hello world"']
##
initContainers: {}

extraLabels: {}

service:
  annotations: {}
  ## If service type NodePort, define the value here
  #ldapPortNodePort:
  #sslLdapPortNodePort:

  # Disable if you do not want to expose port on service
  enableLdapPort: true
  enableSslLdapPort: true

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  ## Define a static clusterIP
  #clusterIP:
  #loadBalancerIP:
  #loadBalancerSourceRanges: []
  type: ClusterIP
  sessionAffinity: None
  externalTrafficPolicy: Cluster

  ## Represents the dual-stack-ness requested or required by this Service. Possible values are
  ## SingleStack, PreferDualStack or RequireDualStack.
  ## The ipFamilies and clusterIPs fields depend on the value of this field.
  ## Ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/
  ipFamilyPolicy: SingleStack

# Service for read only cluster pods (if enabled)
serviceReadOnly:
  annotations: {}
  ## If service type NodePort, define the value here
  #ldapPortNodePort:
  #sslLdapPortNodePort:

  # Disable if you do not want to expose port on service
  enableLdapPort: true
  enableSslLdapPort: true

  # Control ports used in statefulset
  headlessEnableLdapPort: true
  headlessEnableSslLdapPort: true

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  ## Define a static clusterIP
  #clusterIP:
  #loadBalancerIP:
  #loadBalancerSourceRanges: []
  type: ClusterIP
  sessionAffinity: None
  externalTrafficPolicy: Cluster

  ## Represents the dual-stack-ness requested or required by this Service. Possible values are
  ## SingleStack, PreferDualStack or RequireDualStack.
  ## The ipFamilies and clusterIPs fields depend on the value of this field.
  ## Ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/
  ipFamilyPolicy: SingleStack

# Pod Disruption Budget for Stateful Set
# Disabled by default, to ensure backwards compatibility
pdb:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""

## @param customLivenessProbe Custom livenessProbe that overrides the default one
##
customLivenessProbe: {}
## @param customReadinessProbe Custom readinessProbe that overrides the default one
##
customReadinessProbe: {}
## @param customStartupProbe Custom startupProbe that overrides the default one
##
customStartupProbe: {}
## Configure Pods Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param podSecurityContext.enabled Enabled OPENLDAP  pods' Security Context
## @param podSecurityContext.fsGroup Set OPENLDAP  pod's Security Context fsGroup
##
podSecurityContext:
  enabled: true
  fsGroup: 1001
## Configure Container Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param containerSecurityContext.enabled Enabled OPENLDAP  containers' Security Context
## @param containerSecurityContext.runAsUser Set OPENLDAP  containers' Security Context runAsUser
## @param containerSecurityContext.runAsNonRoot Set OPENLDAP  containers' Security Context runAsNonRoot
##
containerSecurityContext:
  enabled: false
  runAsUser: 1001
  runAsNonRoot: true

## @param existingConfigmap The name of an existing ConfigMap with your custom configuration for OPENLDAP
##
existingConfigmap:
## @param command Override default container command (useful when using custom images)
##
command: []
## @param args Override default container args (useful when using custom images)
##
args: []
## @param hostAliases OPENLDAP  pods host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []
## @param podLabels Extra labels for OPENLDAP  pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}
## @param podAnnotations Annotations for OPENLDAP  pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## @param tolerations Tolerations for OPENLDAP  pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
## @param updateStrategy.type OPENLDAP  statefulset strategy type
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
##
updateStrategy:
  ## StrategyType
  ## Can be set to RollingUpdate or OnDelete
  ##
  type: RollingUpdate
## @param priorityClassName OPENLDAP  pods' priorityClassName
##
priorityClassName: ""
## @param schedulerName Name of the k8s scheduler (other than default) for OPENLDAP  pods
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
schedulerName: ""
## @param lifecycleHooks for the OPENLDAP  container(s) to automate configuration before or after startup
##
lifecycleHooks: {}

## Service Account
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  ## @param serviceAccount.create Enable creation of ServiceAccount for Apache pod
  ##
  create: true
  ## @param serviceAccount.name The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the common.names.fullname template
  ##
  name: ""
  ## @param serviceAccount.automountServiceAccountToken Allows auto mount of ServiceAccountToken on the serviceAccount created
  ## Can be set to false if pods using this serviceAccount do not need to use K8s API
  ##
  automountServiceAccountToken: false
  ## @param serviceAccount.annotations Additional custom annotations for the ServiceAccount
  ##
  annotations: {}  

## Configure extra options for liveness, readiness, and startup probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10
startupProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 30

## test container details
test:
  enabled: false
  image:
    repository: dduportal/bats
    tag: 0.4.0

## phpldapadmin
## For more parameters check following file: ./charts/phpldapadmin/values.yaml
phpldapadmin:
  enabled: true
  ldap:
    starttls: false
    allowGuest: false
  ingress:
    enabled: true
    annotations: {}
    ## See https://kubernetes.io/docs/concepts/services-networking/ingress/#ingressclass-scope
    # ingressClassName: nginx
    path: /
    pathType: Prefix
    ## Ingress Host
    hosts:
    - phpldapadmin.example
    ## Ingress cert
    tls: []
    # - secretName: phpldapadmin.example
    #   hosts:
    #   - phpldapadmin.example

## ltb-passwd
# For more parameters check following file: ./charts/ltb-passwd/values.yaml
ltb-passwd:
  enabled : true
  ldap:
    searchBase: "dc=example,dc=com"
    starttls: false
# passwordPolicy:
#   minLength: 16
#   maxLength: 32
#   showPolicy: onerror
  ingress:
    enabled: true
    annotations: {}
    # See https://kubernetes.io/docs/concepts/services-networking/ingress/#ingressclass-scope
    # ingressClassName: nginx
    path: /
    pathType: Prefix
    ## Ingress Host
    hosts:
    - "ssl-ldap2.example"
    ## Ingress cert
    tls: []
    # - secretName: ssl-ldap2.example
    #   hosts:
    #   - ssl-ldap2.example
