apiVersion: v2
name: phpldapadmin
home: http://phpldapadmin.org
version: 1.0.0
appVersion: 2.3.10
description: Web based LDAP administration tool
keywords:
  - ldap
  - openldap
  - iam-stack
  - administration
icon: https://raw.githubusercontent.com/leenooks/phpLDAPadmin/master/public/images/logo.png
sources:
  - https://github.com/reprostat/helm-openldap/tree/main/charts/phpldapadmin
  - https://github.com/leenooks/phpLDAPadmin/tree/master/docker
maintainers:
  - name: Tibor Auer
    email: tibor.auer@gmail.com
