apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "phpldapadmin.fullname" . }}
  labels:
    app: {{ template "phpldapadmin.name" . }}
    chart: {{ template "phpldapadmin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  APP_DEBUG: "{{ if .Values.debug }}true{{ else }}false{{ end }}"
  LDAP_HOST: {{ include "global.server" . | default .Values.ldap.host }}
  LDAP_CONNECTION: "{{ if .Values.ldap.starttls }}starttls{{ else }}plain{{ end }}"
  LDAP_BASE_DN: {{ (include "global.baseDomain" .) | default .Values.ldap.baseDn }}
  LDAP_LOGIN_ATTR: {{ .Values.ldap.loginAttribute | default "dn" }}
  LDAP_LOGIN_ATTR_DESC: {{ .Values.ldap.loginAttributeDesc | default "Distinguished Name (DN)" }}
  LDAP_LOGIN_OBJECTCLASS: {{ .Values.ldap.loginObjectClass | default "inetOrgPerson,posixAccount" }}
  LDAP_ALLOW_GUEST: "{{ if .Values.ldap.allowGuest }}true{{ else }}false{{ end }}"
  LDAP_USERNAME: "cn=admin,{{ (include "global.baseDomain" .) | default .Values.ldap.baseDn }}"
  