apiVersion: v2
name: ltb-passwd
home: https://self-service-password.readthedocs.io
version: 1.0.0
appVersion: "1.7.3"
description: LDAP Tool Box Self Service Password
keywords:
  - ldap
  - openldap
  - iam-stack
  - self-service
sources:
  - https://github.com/reprostat/helm-openldap/tree/master/charts/ltb-passwd
  - https://github.com/ltb-project/self-service-password/tree/master/packaging/docker
maintainers:
  - name: Tibor Auer
    email: tibor.auer@gmail.com
