# Default values for ltb-passwd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ltbproject/self-service-password
  tag: 1.7.3
  pullPolicy: IfNotPresent
  pullSecrets: []


nameOverride: ""
fullnameOverride: ""

debug: "false"

ldap:
  host: localhost
  baseDn: dc=example,dc=com
  searchBase: "dc=example,dc=com"
  starttls: false
  tlsSecretName: ldap-tls
  bindDnSecretName: ldap-bind # Secret containing the password for the bind DN as LDAP_ADMIN_PASSWORD
  loginAttribute: uid

passwordPolicy:
  hash: auto
  minLength: 8
  maxLength: 32
  minLower: 0
  minUpper: 0
  minDigit: 0
  minSpecial: 0
  forbiddenChars: "$"
  noSpecialAtEnds: false
  usePwnedPasswords: false
  noReuse: false
  showPolicy: never

service:
  type: ClusterIP
  port: 80

## Configure Ingress based on the documentation here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  annotations: {}
  ## See https://kubernetes.io/docs/concepts/services-networking/ingress/#ingressclass-scope
  # ingressClassName: nginx
  path: /
  ## Ingress Host
  # hosts:
  # - ssl-ldap.local
  #
  tls: []
  # tls:
  # - secretName: ssl-ldap-dedicated-tls
  #   hosts:
  #   - ssl-ldap.local

# -- Init containers to add to the pod
## Note: Supports use of custom Helm templates
initContainers: []

# -- Additional volumeMounts to the application main container
volumeMounts: []
#  - mountPath: /usr/local/bin/my_tool
#    name: xxxxxx
#    subPath: foo

# -- Additional volumes to the application pod
volumes: []
#  - name: xxxxx
#    emptyDir: {}
resources: {}
#  limits:
#    cpu: 100m
#    memory: 64Mi
#  requests:
#    cpu: 50m
#    memory: 32Mi
nodeSelector: {}
tolerations: []
affinity: {}
  