name: Test-InitTLSWrite
on:
  workflow_call:
jobs:
  qualif:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Run custom action
      # Use the location in the repository (without action.yml)
      uses: ./.github/actions/setup
      with:
        install-chaos: false
    - name: deploy openldap with inittls and write
      shell: bash
      run: |
        cd "$GITHUB_WORKSPACE"
        helm -n tlswrite install openldap  --create-namespace -f .bin/tlswrite-values.yaml .
        kubectl -n tlswrite rollout status sts openldap
    - name: verify inittls and write deployment
      shell: bash
      run: |
          echo "test access to openldap database"
          echo "Write test to openldap database"
          LDAPTLS_REQCERT=never ldapadd -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -f .bin/tlswriteUser.ldif
          sleep 10
          LDAPTLS_REQCERT=never ldapsearch -o nettimeout=20 -x -D 'cn=admin,dc=example,dc=org' -w Not@SecurePassw0rd -H ldaps://localhost:30636 -b 'dc=example,dc=org' > /tmp/test-write.txt
          cat /tmp/test-write.txt
          if [ $(grep "numResponses" /tmp/test-write.txt | cut -d ":" -f 2 | tr -d ' ') -ne 5 ]; then exit 1 ; fi
